name: RopesPlugin
main: tld.sima.ropesplugin.Main
version: 0.1
author: Simon A
description: A plugin that allows users to deploy ropes

commands:
  rope:
    description: Get rope tool
    usage: /rope
    permission: Ropes.use
    permission-message: You don't have the Ropes.use permission.
